### PR TITLE
fix: python3 sort

### PR DESCRIPTION
**Pull request by YuHoYe**
fix TypeError: '<' not supported between instances of 'dict' and 'dict'

### CODE REVIEW

**Comment by harrtho** [comment]
Hi @YuHoYe , thank you for the pull request. 

Can you please tell me which version of python3 you use?
Can you please tell me which version of Alfred you use?

I can't reproduce the error. Can you please give me an example of the filter input values?

> Please keep in mind when you use the filter function:
> ```
> :param key: function to get comparison key from ``items``. Must return a ``str`` string.
>				The default simply returns the item.
> :type key: ``callable``
> ```

**Comment by YuHoYe** [comment]
Python 3.11.4 & Alfred 5.1.4

My example is below:

` repos = wf.filter(key, projects, key=lambda x: x['name'])`

key is `L`

projects is `[
  {
    "name": "nameA",
    "web_url": "urlA",
    "namespace": "nameSpaceA"
  },
  {
    "name": "nameB",
    "web_url": "urlB",
    "namespace": "nameSpaceB"
  }
]`

>  14:16:24 workflow.py:2502 ERROR    '<' not supported between instances of 'dict' and 'dict'
Traceback (most recent call last):
  File "/Users/yuho/Nutstore Files/Tools/Alfred/Alfred.alfredpreferences/workflows/user.workflow.874F0102-B092-45EA-872E-E75A0D8511AE/workflow/workflow.py", line 2495, in run
    func(self)
  File "/Users/yuho/Nutstore Files/Tools/Alfred/Alfred.alfredpreferences/workflows/user.workflow.874F0102-B092-45EA-872E-E75A0D8511AE/main.py", line 64, in main
    search_repo_in_cache(wf, args.repo)
  File "/Users/yuho/Nutstore Files/Tools/Alfred/Alfred.alfredpreferences/workflows/user.workflow.874F0102-B092-45EA-872E-E75A0D8511AE/main.py", line 22, in search_repo_in_cache
    repos = wf.filter(key, projects, key=lambda x: x['name'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuho/Nutstore Files/Tools/Alfred/Alfred.alfredpreferences/workflows/user.workflow.874F0102-B092-45EA-872E-E75A0D8511AE/workflow/workflow.py", line 2331, in filter
    results.sort(reverse=ascending)
TypeError: '<' not supported between instances of 'dict' and 'dict'

**Comment by harrtho** [comment]
Hey @YuHoYe,

I made an example with your input and attached it. The filter is working as intended and I can't reproduce any misbehavior. Please rename the attached workflow from ".zip" to ".alfredworkflow" and take a look.

Bildschirmfoto 2023-11-11 um 10 56 10
[Filter Example.zip](https://github.com/harrtho/alfred-pyworkflow/files/13325146/Filter.Example.zip)

**Comment by YuHoYe** [comment]
I’ve identified a way to reproduce the error.
Please adjust the example `PROJECTS` as detailed below:

 ```
PROJECTS = [
    {"name": "nameA", "web_url": "urlA", "namespace": "nameSpaceA"},
    {"name": "nameA", "web_url": "urlA_1", "namespace": "nameSpaceA_1"},
    {"name": "nameB", "web_url": "urlB", "namespace": "nameSpaceB"},
    {"name": "nameC", "web_url": "urlC", "namespace": "nameSpaceC"}
]
```

If you search `a`, you will get the same error. But if you search `b`, it works well.

**Comment by harrtho** [comment]
Hi @YuHoYe ,

now I can see what you mean. Thank you very much!

I need to change your PR a little as `key=lamda x: x[1][1]` would only point to the score of the result tuple. In fact the results list elements are tuple that contain 2 tuple `[((sorting/keys), (result)), ...]`. The first tuple is for the sorting algorithm and the second is the actual result. In your example the content of the `sorting/keys` tuple is the same, the `sort` algorithm continues with the `result` tuple to find any differences until it reaches the result `dict`. Sorting dicts was possible in python2  but it is not longer in python3. Now we need to limit the sorting to the fist tuple only `key=lamda x: x[0]` and all it's elements.

**Comment by harrtho** [comment]
The change is now in main. I will create a Release later this week. Please let me know if we can close this PR.

**Comment by YuHoYe** [comment]
> The change is now in main. I will create a Release later this week. Please let me know if we can close this PR.

Sure, I will close it.

**Pull request closed without merging**
